Pre-Publish Checklist: Add check for missing publisher logo
google/web-stories-wp pull request #9323
Opened 2021-10-07 20:36 UTC by samwhale

## Context

The "publisher logo too small" check was showing when there was no publisher logos

## Summary

Adds a publisher logo existence card to the checklist and prevents the 'publisher logo too small' card from showing.

## Relevant Technical Choices

n/a

## To-do

n/a

## User-facing changes

![existence](https://user-images.githubusercontent.com/22185279/136458132-76219e5e-af20-4d10-9e28-52c434c35d7c.gif)

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Delete all of the publisher logos in your app. This can be done by running `npm run env:reset-site` (which blows up everything) or deleting the media one by one from the media library
<img src="https://user-images.githubusercontent.com/22185279/136458204-7f7b76d8-4e2c-4475-9b30-1598150198d6.png" height="200px" />
2. Create a new story from a template (easiest since it has a lot of pages)
3. Open the checklist. See the new card in the priority section
4. Click the card - should highlight the publisher logo section like in the gif

## Reviews

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9320

2021-10-07 20:39 UTC, samwhale commented on packages/story-editor/src/components/checklist/checklistContent/accessibilityChecks.js
> +      isExpanded={Boolean(badgeCount) && isOpen}
Proptype was failing because `badgeCount` is a number. When it is `0` then isExpanded is not a boolean

2021-10-07 22:41 UTC, BrittanyIRL requested changes
Thanks for whipping this up so fast! 

Needs a little extra check for when the logo id is 0, then i think it's good!

2021-10-07 22:41 UTC, BrittanyIRL commented on packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js
> +  return !(publisherLogo?.id || publisherLogo?.url);
Since a publisher logo can have an id of 0, let's make sure that's not returning true and showing this check. 
(reset site and uploaded 1 logo)
![Screen Shot 2021-10-07 at 3 37 39 PM](https://user-images.githubusercontent.com/10720454/136471819-2d335851-c135-4ded-80da-9bca8e195449.png)

(publisherLogo logged before return)
<img width="368" alt="Screen Shot 2021-10-07 at 3 40 09 PM" src="https://user-images.githubusercontent.com/10720454/136471856-e4b8ac25-bbbb-48cf-9fb4-23a196fe6eb0.png">

2021-10-07 22:47 UTC, BrittanyIRL commented on packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js
> +  return !(publisherLogo?.id || publisherLogo?.url);
```suggestion
  return Boolean(publisherLogo?.id || publisherLogo?.url);
```

This will fix it

2021-10-08 09:27 UTC, spacedmonkey commented
SGTM

2021-10-08 13:27 UTC, samwhale commented on packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js
> +  return !(publisherLogo?.id || publisherLogo?.url);
I thought publisher logos couldn't have an id of zero 🤔 

So to make sure we don't have one, should we just check that there's no url, no height, and no width? Since `id === 0` doesn't guarantee that there's no publisher logo?

2021-10-08 13:42 UTC, swissspidy commented on packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js
> +  return !(publisherLogo?.id || publisherLogo?.url);
I think what Brittany is saying that right now when there is no publisher logo we return an "empty" object with `id === 0` instead of `null`. Something we're probably going to change.

Checking for something like `const hasPublisherLogo = Boolean(publisherLogo?.id)` should be enough

2021-10-08 15:13 UTC, samwhale commented on packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js
> +  return !(publisherLogo?.id || publisherLogo?.url);
>Checking for something like const hasPublisherLogo = Boolean(publisherLogo?.id) should be enough

Currently if there is no publisher logo then the publisher logo on in the story context is `{ id: 0, height: 0, width: 0, url: '' }`, so the `hasPublisherLogo` check would always be true.

Once the stored 'empty state' of the publisher logo changes to `null` that will work but for now I think it needs to check if the id is `0`, no? Unless I'm just having major Friday brain

2021-10-08 15:45 UTC, swissspidy commented on packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js
> +  return !(publisherLogo?.id || publisherLogo?.url);
> Once the stored 'empty state' of the publisher logo changes to null that will work but for now I think it needs to check if the id is 0, no?

If you coerce `0` to a `boolean` it will be `false`. Just what we want.

```js
const publisherLogo = { id: 0 }
const hasPublisherLogo = Boolean(publisherLogo?.id) // this will be false. exactly what we want.
```

2021-10-08 15:46 UTC, swissspidy commented on packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js
> +}
```suggestion
export function publisherLogoExistence(publisherLogo) {
  return !(publisherLogo?.id);
}
```

2021-10-08 15:49 UTC, swissspidy commented on packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js
> +}
Also, FWIW, this function checks whether the logo is **missing**, but the function is named publisherLogo_Existence_. That is super confusing.

Either rename this to `publisherLogoInexistence` (which is also confusing), or reverse the check:

```suggestion
/**
 * Determines whether a publisher logo exists.
 * @param {Object} publisherLogo Publisher logo object.
 * @return {boolean} Whether a publisher logo exists.
 */
export function publisherLogoExistence(publisherLogo) {
  return Boolean(publisherLogo?.id);
}
```

Of course update `PublisherLogoExistence` below accordingly

2021-10-08 15:50 UTC, swissspidy commented on packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js
> +  return !(publisherLogo?.id || publisherLogo?.url);
No need for the `url` check really. Just checking for the ID is enough.

2021-10-08 16:52 UTC, samwhale commented on packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js
> +  return !(publisherLogo?.id || publisherLogo?.url);
Oh wait we're saying the same thing 😮‍💨 okay, it should be updated correctly now.

2021-10-08 16:53 UTC, BrittanyIRL commented on packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js
> +}
+1 for `PublisherLogoMissing`

2021-10-08 18:18 UTC, maxyinger approved these changes

2021-10-08 19:33 UTC, samwhale commented on packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js
> +}
Ah good shout

2021-10-08 20:00 UTC, BrittanyIRL approved these changes
👍

2021-10-10 15:46 UTC, merged