Page Templates: Always show images when applying default template
google/web-stories-wp pull request #9538
Opened 2021-10-26 19:37 UTC by BrookeGraham

## Context

In the default templates layout, we no longer want to show the placeholder grid image. Instead we want to show the default images that are associated with the template. 

If a user has not seen the help center tip about adding background images, we want to show that tip when they add a default template as a page. 

## Summary

## Relevant Technical Choices

## To-do

## User-facing changes

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add a default template as a page in the editor.
2. You should now see any and all images on the canvas that were present in the thumbnail view. (No placeholder grid image)

## Reviews

### Does this PR have a security-related impact?
no

### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9536

2021-10-26 19:42 UTC, maxyinger approved these changes
looks good!

2021-10-26 19:42 UTC, maxyinger commented on packages/story-editor/src/components/library/panes/pageTemplates/defaultTemplateList.js
> +      }
`openToUnreadTip` already checks if the tip has been read before opening, so you shouldn't need to check `readTips` here

2021-10-26 19:42 UTC, maxyinger commented on packages/story-editor/src/components/library/panes/pageTemplates/defaultTemplateList.js
> +    actions: { openToUnreadTip = noop },
I think `openToUnreadTip` should always be defined. any reason why you defaulted it to a `noop` here?

2021-10-26 20:22 UTC, swissspidy commented
You may want to incorporate #9529 into this PR since this results in a lot of now unused code.

> If a user has not seen the help center tip about adding background images, we want to show that tip when they add a default template as a page.

What's the rationale behind this? 🤔 

Not all templates have background images. And some do, but for those the "Replace media" quick action can be used.

2021-10-26 20:41 UTC, BrookeGraham commented on packages/story-editor/src/components/library/panes/pageTemplates/defaultTemplateList.js
> +    actions: { openToUnreadTip = noop },
Oh I saw that there was a default given in another part of the codebase so I copied the implementation. But yeah it looks like it should always be defined. I can remove.

2021-10-26 20:49 UTC, BrookeGraham commented
@swissspidy 

> >If a user has not seen the help center tip about adding background images, we want to show that tip when they add a default template as a page.
>
> What's the rationale behind this? 🤔

During bugbash we discussed showing the help center tip as a way of letting people know that the images are essentially placeholders. So if they hadn't seen the tip yet, we should show it once they add a default template that has a stock image.  The background image tip was the closest tip I saw that would make sense since a "replace stock images" tip doesn't exist. 🤷🏻‍♀️

2021-10-26 22:48 UTC, BrittanyIRL reviewed
right on. 

i agree with pascal that deleting the dead code around the grid version of these (see his PR #9529) would keep things tidy, if you've got time tomorrow. 

thanks for also getting the help center update in here!  You'll want to make sure to leave claudio a note in the ticket about clearing that state and what to expect as you move it to QA.

2021-10-26 22:48 UTC, BrittanyIRL commented on packages/story-editor/src/components/library/panes/pageTemplates/defaultTemplates.js
> +      setPageTemplates(await getPageTemplates({ showImages: true }));
🤝

2021-10-26 22:49 UTC, BrookeGraham commented on packages/story-editor/src/components/library/panes/pageTemplates/karma/pageTemplatesPane.karma.js
> -      // make next template "Entertainment Section" active before leaving template list
I removed these because now that the quick tips pops up keyboard navigation is a bit different. Since these are getting an [upgrade](https://github.com/google/web-stories-wp/pull/9509), I figured we can clean this part up in that pr.

2021-10-27 15:40 UTC, swissspidy commented on packages/story-editor/src/components/library/panes/pageTemplates/defaultTemplates.js
> +      setPageTemplates(await getPageTemplates({ showImages: true }));
```suggestion
      setPageTemplates(await getPageTemplates());
```

2021-10-27 15:40 UTC, swissspidy commented on packages/story-editor/src/app/api/apiProvider.js
>      withoutImages: [],
No longer needed

2021-10-27 15:41 UTC, swissspidy commented on packages/story-editor/src/app/api/apiProvider.js
> +    return pageTemplates.current.base;
```suggestion
    // check if pageTemplates have been loaded yet
    if (pageTemplates.current.length === 0) {
      pageTemplates.current= await getAllTemplates({ cdnURL });
    }

    return pageTemplates.current;
```

we could now simplify this ref a bit (see also comment above)

2021-10-27 18:18 UTC, BrittanyIRL requested changes
🤔  this is crashing the editor right now when i navigate to page templates, are you seeing this as well? 

![Screen Shot 2021-10-27 at 11 13 57 AM](https://user-images.githubusercontent.com/10720454/139123708-55e829b5-7ef1-402e-b64c-4f1a61b63dbf.png)

2021-10-27 18:56 UTC, BrookeGraham commented
@BrittanyIRL  I did get that at one point after adding those clean up tasks. But I thought I had fixed it. Let me take a look. Working on fixing some of the tests I broke while doing that same bit of "clean up"

2021-10-27 19:02 UTC, BrookeGraham commented
> 🤔 this is crashing the editor right now when i navigate to page templates, are you seeing this as well?

Found it. pushing up a change here in just a bit.

2021-10-27 19:28 UTC, BrittanyIRL commented on packages/story-editor/src/components/library/panes/pageTemplates/defaultTemplateList.js
>      },
I'm sorry i didn't active enough yesterday to catch this. Discussing in this thread here: https://xwp.slack.com/archives/C01ESBB8ZN1/p1635362628028200?thread_ts=1635359374.026100&cid=C01ESBB8ZN1 let's not add this trigger here, the copy doesn't make enough sense to have it expand, it should be a tip but it should be it's own tip. I'll add a ticket for that now and follow up here.

-- update --
Follow up ticket: https://github.com/google/web-stories-wp/issues/9560

2021-10-27 19:37 UTC, BrookeGraham commented on packages/story-editor/src/components/library/panes/pageTemplates/defaultTemplateList.js
>      },
Great. I will remove!

2021-10-27 20:53 UTC, BrittanyIRL approved these changes
🎉  perf - thanks for the quick updates.

2021-10-28 15:13 UTC, samwhale approved these changes
Nice, works great! I think we could refactor the way page templates are stored in that ref (if we want to). Don't need the `base` property anymore

2021-10-28 15:13 UTC, samwhale commented on packages/story-editor/src/app/api/apiProvider.js
>      base: [],
we could update this to not use the `base` property at all since we just need this one array now

Something like

```js
const pageTemplates = useRef([]);
```

2021-10-28 15:13 UTC, samwhale commented on packages/story-editor/src/components/library/panes/pageTemplates/karma/pageTemplatesPane.karma.js
> +        ).toBe(0);
🤔 Is the sleep needed here?

2021-10-28 15:27 UTC, BrookeGraham commented on packages/story-editor/src/components/library/panes/pageTemplates/karma/pageTemplatesPane.karma.js
> +        ).toBe(0);
The damn test would fail unless I was running in slowMo so I added it for a buffer to allow time for the options to get removed.

2021-10-28 15:28 UTC, BrookeGraham commented on packages/story-editor/src/app/api/apiProvider.js
>      base: [],
Makes sense.

2021-10-28 15:28 UTC, samwhale commented on packages/story-editor/src/components/library/panes/pageTemplates/karma/pageTemplatesPane.karma.js
> +        ).toBe(0);
sounds good! Maybe we could add a little comment about why that's there then :)

2021-10-28 15:31 UTC, BrookeGraham commented on packages/story-editor/src/components/library/panes/pageTemplates/karma/pageTemplatesPane.karma.js
> +        ).toBe(0);
Yeah. I have an [open pr](https://github.com/google/web-stories-wp/pull/9509) that is moving these tests. And adds more. I can just do that there?

2021-10-28 15:34 UTC, samwhale commented on packages/story-editor/src/components/library/panes/pageTemplates/karma/pageTemplatesPane.karma.js
> +        ).toBe(0);
that works!

2021-10-28 22:27 UTC, merged